apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowledge
  template:
    metadata:
      labels:
        app: knowledge
    spec:
      containers:
      - name: knowledge
        image: saromanov/knowledge
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8044